package com.example.walletledger.adapters.web.dto;

public enum ErrorCode {
    VALIDATION_FAILED,
    ACCOUNT_NOT_FOUND,
    SAME_ACCOUNT_TRANSFER,
    CURRENCY_MISMATCH,
    INSUFFICIENT_FUNDS,
    IDEMPOTENCY_KEY_REUSED,
    TRANSFER_IN_PROGRESS,
    RATE_LIMIT_EXCEEDED,
    METHOD_NOT_ALLOWED,
    RESOURCE_NOT_FOUND,
    UNSUPPORTED_MEDIA_TYPE,
    INTERNAL_ERROR
}
